sudo: required
services:
  - docker

env:
  global:
    - secure: "CwC8kcW+DP1t21R3gFNr3jskcNSre9W7ztstL+fa2R9AE8rkli9VHJ1qajbOjlzsjUOZFR8mGftwHHHKcPbyn0jpLNnFOj3JSmq+DyVpiizQjr+QJyqwhr4OTfzcKSxe9AUFlHu7kHNj5Ccs0sA4cqnp4Zk7Byt8GoKo5OOiFWjS3oLmFRkBhhycLGZ80k98cces600dgm6+1/pnwCc5g/40GSGKsIxX6mT2b6drVxs3yzKejf5HtN8OiBhj+Kh/q9C2cFtYBcQ0llyhQPhaS2qGz2CJsL97322vxoizUPPz9ULlPvQkFynEMBAvO3mqN5+AYnS8UnuZrp+iOP6ouPls//a8OkqwBLGNVi4dn+tuwtfEZiELwa8k73UTfmKdNCtwPT4ROKvC+hXq+xsLlW5PW3U7mIk25XdjHY8sGyUVQ44mG8VR0d8lVZz20WkoIq/Hb/fXwcWb/IFN0M/FVBSNy+XXbM6BOP1zJYG/ovGq67VNVnphkQuYlh2h8tsKHa7bW3JQM9PTJcGiSOrQx5Et60bUVULhkKwfnBSy6LNRsidEIjKuUCSBUCt5MARJnWTGQqXw+o/hGSGRkeiPiGjBNMNfqaUJlCJGlYazikhdElbEeBQBeB3O1sEjQ8RdLQAkut2IiVoQBOUcFSgFFTKMnyrauOVKkUWYCpsY85w="

language: go
go: 1.8

install:
  - curl https://glide.sh/get | sh
script:
  - glide install
  - go test -v -cover
  - go vet -x
  - mkdir -p bin
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/drone-trigger_linux_amd64
  - GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/drone-trigger_linux_386
  - GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/drone-trigger_linux_arm
  - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/drone-trigger_darwin_amd64
  - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.Version=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/drone-trigger_windows_amd64.exe
  - if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_EVENT_TYPE} == "push" ]]) || [[ -n ${TRAVIS_TAG} ]]; then
    docker login -u "ukhomeofficedigital+drone_trigger" -p ${DOCKER_PASSWORD} quay.io;
    docker build -t quay.io/ukhomeofficedigital/drone-trigger:${TRAVIS_TAG:-latest} .;
    docker push quay.io/ukhomeofficedigital/drone-trigger:${TRAVIS_TAG:-latest};
    fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Z0VPkgJ2TYY2E66Z3Np2CmIOiSb6jfTtKAijmjyP9BNprxQpqpTIGch1RU3tFRj79rab7lOCJ/jUr4F1pOth4JjMWWmhoKLsSEP6KphSgapuh4++TU/9+Qy0hCvOYW5+HP/TozGwFcjEJvD6W3jOZbYh0jbKIFPifXJNraWzKddSaYkww94ZgN/m2sjygO5cOvrvKqwMoBKaKpJWbZ8JMvgBf+jbwtMwbMXMFg4OW4CLMKpRibY7IEQOHHogYV9s+ly32jFyrpFNaP5CMeho6KE3KmJQaYn21mcDSFrBS90xtJGPdJwVbutuPZ04y1J+IypfgIJ7qBxewTRmsxWcn2Ziyg3gwP/bCmVQzOXA8+/ZFaax/WCdbXyzF2kRXlpU23C5lWbtQKO02B657xD6GOs9vB76UjWx9yEpmzV3OwSsqFz0IjMDt6VhjYTtkK30AV2XapykroHgshpug7K7mMdruugU9g6jjRKFyx0ITd6njNFrbBN009DawlRRrOhPoh6dPJ/fu6gbgTyk3AIjKBRlE6U6t97OUiPaLXAAUL/JrHwYvU/PFaNm1kxzvLevqJAIChU2eIViB2tRgdQiEWIyIQEV2KiyoY3w05BscFLB45TiyYkogYaxrvXimFfFx6fXl7Luk1lFNmPqIsH7ttgp+2bagYegNHS1hFGqS00=
  file:
    - bin/drone-trigger_linux_amd64
    - bin/drone-trigger_linux_386
    - bin/drone-trigger_linux_arm
    - bin/drone-trigger_darwin_amd64
    - bin/drone-trigger_windows_amd64.exe
  on:
    tags: true
    repo: UKHomeOffice/drone-trigger
